version: "3.3"
services:
  mqpconsumer:
    container_name: consumer_maaike_test
    build: .
    env_file: env_file

    stdin_open: true
    tty: true

    logging:
      driver: ${LOG_DRIVER}
      options:  
        loki-url: ${LOKI_URL} 
        loki-pipeline-stages: |
          - regex:
              expression: ^(?P<severity>[\w\.]+):(?P<pymodule>[\w]+)
          - labels:
              severity:
              pymodule:
        labels: container_name,host,severity,pymodule

